---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: consent-service
  namespace: consent-service
  labels:
    app: consent-service
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: consent-service
    kind: SecretStore
  target:
    name: consent-service-aws-secret-manager
    creationPolicy: Owner
    template:
      data:
        config: |
          {
            "configuration_name" : "Local Development",
            "credentials": {
              "db": {
                "configuration_name" : "environment_working_on",
                "host": "{{ .postgresqlhostname }}",
                "port": 5432,
                "database": "database_name",
                "user": "{{ .postgresqlusername }}",
                "password": "{{ .postgresqlpassword }}"
              }
            }
          }
  data:
  - secretKey: postgresqlpassword
    remoteRef:
      key: be/rds/ops-adminportal/postgres-password
  - secretKey: postgresqlusername
    remoteRef:
      key: be/rds/ops-adminportal/postgres-user
  - secretKey: postgresqlhostname
    remoteRef:
      key: be/rds/ops-adminportal/hostname
