---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: consent-service
  namespace: consent-service
  labels:
    app: consent-service
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret
