---
apiVersion: v1
kind: Service
metadata:
  name: consent-service
  namespace: consent-service
spec:
  selector:
    app: consent-service
  ports:
    - protocol: TCP
      port: 8180
      targetPort: go
  type: ClusterIP
