---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secret
  namespace: consent-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::353554545:role/be-external-secret-secretmanager
